### PR TITLE
20240523 ensure to regenerate lockfiles if vendor set to false

### LINKED ISSUE #82: feature request: have an option to create vendor tarballs with locked versions
It would be useful to have an option to create vendor tarballs with locked versions, so that in such cases we don't have to create the tarball ourselves.
For context: https://github.com/ast-grep/ast-grep/issues/1118

### PR DESCRIPTION
**Pull request by uncomfyhalomacro**
Might close #82 not sure if that fixes that

### CODE REVIEW

**Comment by uncomfyhalomacro** [comment]
uh i am so dumb. wait. i will put another commit. `cargo update` already generates lockfiles so i am just doing it twice. lmao

**Review by Firstyear — CHANGES_REQUESTED** [review]
If we now always have a lock file ahead of time, then we can do https://github.com/Firstyear/obs-service-cargo/blob/master/cargo/src/vendor.rs#L65 --locked here yes?

**Comment by Firstyear** [comment]
Oh true.

**Comment by uncomfyhalomacro** [comment]
> Cargo vendor occurs online by necessity, so we need --locked at this point just in case (even though cargo vendor shouldn't update anything ...)

i will be implementing frozen and lock first to coreos/cargo-vendor-filterer in a bit.

**Review by Firstyear — APPROVED** [review]

**Pull request merged**
